 var source = {
    matrix: [
        //row
    [
        {abbr:'H', latinName:'Hydrogenium', name:'Hydrogen', number:1, weight:1.00794, elementClassName: 'nonmetal'},
        { className: 'empty'},
        {abbr:'He', latinName:'Helium', name:'Helium', number:2, weight:4.002602, elementClassName: 'noble'}
     ],
     [   {abbr:'Li', latinName:'Lithium', name:'Lithium', number:3, weight:6.941, elementClassName: 'alkali'},
        {abbr:'Be', latinName:'Borium', name:'Boron', number:4, weight:10.811, elementClassName: 'alkaline'},
        { className: 'empty1'},
        {abbr:'B', latinName:'Beryllium', name:'Beryllium', number:5, weight:9.012182,elementClassName: 'semimetal'},
        {abbr:'C', latinName:'Carboneum', name:'Carbon', number:6, weight:39.948, elementClassName: 'nonmetal'},
        {abbr:'N', latinName:'Nitrogenium', name:'Nitrogen', number:7, weight:14.0067, elementClassName: 'nonmetal'},
        {abbr:'O', latinName:'Oxygenium', name:'Oxygen', number:8, weight:14.0067, elementClassName: 'nonmetal'},
        {abbr:'F', latinName:'Fluorum', name:'Fluorine', number:9, weight:18.9984032, elementClassName: 'halogen'},
        {abbr:'Ne', latinName:'Neon', name:'Neon', number:10, weight:20.1797, elementClassName: 'noble'}
         
     ],
     [
        {abbr:'Na', latinName:'Natrium', name:'Sodium', number:11, weight:22.98976, elementClassName: 'alkali'},
        {abbr:'Mg', latinName:'Magnesium', name:'Magnesium', number:12, weight:22.98976, elementClassName: 'alkaline'},
        { className: 'empty1'},
        {abbr:'Al', latinName:'Aluminium', name:'Aluminium', number:13, weight:26.9815386, elementClassName: 'basic'},
        {abbr:'Si', latinName:'Silicium', name:'Silicon', number:14, weight:28.0855,elementClassName: 'semimetal'},
        {abbr:'P', latinName:'Phosphorus', name:'Phosphorus', number:15, weight: 30.973762, elementClassName: 'nonmetal'},
        {abbr:'S', latinName:'Sulphur', name:'Sulfur', number:16, weight: 32.065, elementClassName: 'nonmetal'},
        {abbr:'Cl', latinName:'Chlorum', name:'Chlorine', number:17, weight: 35.453, elementClassName: 'halogen'},
        {abbr:'Ar', latinName:'Argon', name:'Argon', number:18, weight: 39.948, elementClassName: 'noble'} 
     ],
     [
        {abbr:'K', latinName:'Kalium', name:'Potassium', number:19, weight:39.948, elementClassName: 'alkali'},
        {abbr:'Ca', latinName:'Calx',  name:'Calcium', number:20, weight:40.078, elementClassName: 'alkaline'},
        {abbr:'Sc', latinName:'Scandia', name:'Scandium', number:21, weight:44.955912, elementClassName: 'transition'},
        {abbr:'Ti', latinName:'Titans', name:'Titanium', number:22, weight:47.867, elementClassName: 'transition'},
        {abbr:'Vi', latinName:'Vanadium',  name:'Vanadium', number:23, weight:50.9415, elementClassName: 'transition'},
        {abbr: 'Cr', latinName: 'Chromium', name: 'Chromium',  number: 24, weight: 51.9961, elementClassName: 'transition'},
        {abbr: 'Mn', latinName: 'Manganum', name: 'Manganese', number: 25, weight: 54.93045, elementClassName: 'transition'},
        {abbr: 'Fe', latinName: 'Ferrum', name: 'Iron', number: 26, weight: 55.845, elementClassName: 'transition'},
        {abbr: 'Co', latinName: 'Kobold', name: 'Cobalt', number: 27, weight: 58.933195, elementClassName: 'transition'},
        {abbr: 'Ni', latinName: 'Niccolum', name: 'Nickel',  number: 28, weight: 58.6934, elementClassName: 'transition'},
        {abbr: 'Cu', latinName: 'Cuprum', name: 'Copper', number: 29, weight: 63.546, elementClassName: 'transition'},
        {abbr: 'Zn', latinName: 'Zincum', name: 'Zinc', number: 30, weight: 65038, elementClassName: 'transition'},
        {abbr: 'Ga', latinName: 'Gallium', name: 'Gallium', number: 31, weight: 69.723, elementClassName: 'basic'},
        {abbr: 'Ge', latinName: 'Germanium', name: 'Germanium',number: 32, weight: 72.63, elementClassName: 'semimetal'},
        {abbr: 'As', latinName: 'Arsenicum', name: 'Arsenic', number: 33, weight: 74.9216, elementClassName: 'semimetal'},
        {abbr: 'Se', latinName: 'Selenium',  name: 'Selenium', number: 34, weight: 78.96, elementClassName: 'nonmetal'},
        {abbr: 'Br', latinName: 'Bromum',  name: 'Bromine', number: 35, weight: 79.904, elementClassName: 'halogen'},
        {abbr: 'Kr', latinName: 'Kryptonum', name: 'Krypton', number: 36, weight: 83.798, elementClassName: 'noble'} 
],
[
         { abbr: 'Rb',  latinName: 'Rubidium', name: 'Rubidium', number: 37, weight: 85.4678, elementClassName: 'alkali'},
         { abbr: 'Sr', latinName: 'Strontium', name: 'Strontium', number: 38, weight: 87.62, elementClassName: 'alkaline'},
         { abbr: 'Y', latinName: 'Yttrium', name: 'Yttrium', number: 39, weight: 88.90585, elementClassName: 'transition'},
         { abbr: 'Zr', latinName: 'Thallium', name: 'Zirconium', number: 40, weight: 91.224, elementClassName: 'transition'},
         { abbr: 'Nb',  latinName: 'Niobium', name: 'Niobium', number: 41, weight: 92.90628, elementClassName: 'transition'},
         { abbr: 'Mo', latinName: 'Molybdenum', name: 'Molybdenum', number: 42, weight: 95.96, elementClassName: 'transition'},
         { abbr: 'Tc', latinName: 'Tecnetium', name: 'Technetium', number: 43, weight: 98, elementClassName: 'transition'},
         { abbr: 'Ru', latinName: 'Ruthenium', name: 'Ruthentium', number: 44, weight: 101.07, elementClassName: 'transition'},
         { abbr: 'Rh', latinName: 'Kobold', name: 'Rhodium', number: 45, weight: 102.9055, elementClassName: 'transition'},
         { abbr: 'Pd', latinName: 'Palladium', name: 'Palladium', number: 46, weight: 106.42, elementClassName: 'transition'},
         { abbr: 'Ag', latinName: 'Argentum', name: 'Silver', number: 47, weight: 107.8682, elementClassName: 'transition'},
         { abbr: 'Cd', latinName: 'Cadmium', name: 'Cadmium', number: 48, weight: 112.411, elementClassName: 'transition'},
         { abbr: 'In', latinName: 'Gallium', name: 'Indium', number: 49, weight: 114.878, elementClassName: 'basic'},
         { abbr: 'Sn', latinName: 'Germanium', name: 'Tin', number: 50, weight: 118.71, elementClassName: 'basic'},
         { abbr: 'Sb', latinName: 'Arsenicum', name: 'Antimony', number: 51, weight: 121.76, elementClassName: 'semimetal'},
         { abbr: 'Te', latinName: 'Selenium', name: 'Tellurium', number: 52, weight: 127.6, elementClassName: 'semimetal'},
         { abbr: 'I', latinName: 'Bromum', name: 'Iodine', number: 53, weight: 126.90447, elementClassName: 'halogen'},
         { abbr: 'Xe', latinName: 'Kryptonum', name: 'Xenon', number: 54, weight: 131.293, elementClassName: 'noble'}
    ],
    [
         { abbr: 'Cs',  latinName: 'Caesium', name: 'Caesium', number: 55, weight: 132.09054, elementClassName: 'alkali'},
         { abbr: 'Ba', latinName: 'Baryum', name: 'Barium', number: 56, weight: 137.33, elementClassName: 'alkaline'},
         {className: 'empty2'},
         { abbr: 'Hf', latinName: 'Hafnium', name: 'Hafnium', number: 57, weight: 178.49, elementClassName: 'transition'},
         { abbr: 'Ta', latinName: 'Thallium', name: 'Tantalum', number: 58, weight: 180.94788, elementClassName: 'transition'},
         { abbr: 'W',  latinName: 'Wolframium', name: 'Tungesten', number: 59, weight: 183.84, elementClassName: 'transition'},
         { abbr: 'Re', latinName: 'none', name: 'Rhenium', number: 60, weight: 186.207, elementClassName: 'transition'},
         { abbr: 'Os', latinName: 'Osmium', name: 'Osmium', number: 61, weight: 190.23, elementClassName: 'transition'},
         { abbr: 'Ir', latinName: 'Iridium', name: 'Iridium', number: 62, weight: 192.217, elementClassName: 'transition'},
         { abbr: 'Pt', latinName: 'Kobold', name: 'Platinum', number: 63, weight: 195.084, elementClassName: 'transition'},
         { abbr: 'Au', latinName: 'Aurum', name: 'Gold', number: 64, weight: 196.966569, elementClassName: 'transition'},
         { abbr: 'Hg', latinName: 'Hydrargyrum', name: 'Mercury', number: 65, weight: 200.59, elementClassName: 'transition'},
         { abbr: 'Ti', latinName: 'Thallium', name: 'Thallium', number: 66, weight: 204.3833, elementClassName: 'basic'},
         { abbr: 'Pb', latinName: 'Gallium', name: 'Lead', number: 67, weight: 207.2, elementClassName: 'basic'},
         { abbr: 'Bi', latinName: 'Germanium', name: 'Bismuth', number: 68, weight: 208.9804, elementClassName: 'basic'},
         { abbr: 'Po', latinName: 'Arsenicum', name: 'Polonium', number: 69, weight: 209, elementClassName: 'semimetal'},
         { abbr: 'At', latinName: 'Selenium', name: 'Astatine', number: 70, weight: 210, elementClassName: 'halogen'},
         { abbr: 'Rn', latinName: 'Bromum', name: 'Radon', number: 71, weight: 222, elementClassName: 'noble'},
    ],
    [
         { abbr: 'Fr',  latinName: 'Francium', name: 'Francium', number: 72, weight: 223, elementClassName: 'alkali'},
         { abbr: 'Ra', latinName: 'Radium', name: 'Radium', number: 73, weight: 226,elementClassName: 'alkaline'},
         {className: 'empty2'},
         { abbr: 'Rf', latinName: 'Rutherfordium', name: 'Rutherfordium', number: 74, weight: 267,elementClassName: 'transition'},
         { abbr: 'Db', latinName: 'Thallium', name: 'Dubnium', number: 75, weight: 268, elementClassName: 'transition'},
         { abbr: 'Sg',  latinName: 'Seaborgium', name: 'Seaborgium', number: 76, weight: 271, elementClassName: 'transition'},
         { abbr: 'Bh', latinName: 'Bohrium', name: 'Bohtium', number: 77, weight: 272, elementClassName: 'transition'},
         { abbr: 'Hs', latinName: 'Hassium', name: 'Hassium', number: 78, weight: 270, elementClassName: 'transition'},
         { abbr: 'Mt', latinName: 'Meitnerium', name: 'Meitnerium', number: 79, weight: 276, elementClassName: 'transition'},
         { abbr: 'Ds', latinName: 'Kobold', name: 'Darmstadtium', number: 80, weight: 281, elementClassName: 'transition'},
         { abbr: 'Rg', latinName: 'Roentgenium', name: 'Roentgenium', number: 81, weight: 280, elementClassName: 'transition'},
         { abbr: 'Cn', latinName: 'Copernicium', name: 'Copernicium', number: 82, weight: 285, elementClassName: 'transition'},
         { abbr: 'Uut', latinName: 'Unutrium', name: 'Unutrium', number: 83, weight: 284, elementClassName: 'basic'},
         { abbr: 'Fl', latinName: 'Gallium', name: 'Flerovium', number: 84, weight: 289, elementClassName: 'basic'},
         { abbr: 'Uup', latinName: 'Germanium', name: 'Ununpentium', number: 85, weight: 288, elementClassName: 'basic'},
         { abbr: 'Lv', latinName: 'Arsenicum', name: 'Livermorium', number: 86, weight: 293, elementClassName: 'basic'},
         { abbr: 'Uus', latinName: 'Selenium', name: 'Ununseptium', number: 87, weight: 294, elementClassName: 'halogen'},
         { abbr: 'Uuo', latinName: 'Bromum', name: 'Ununoctium', number: 88, weight: 294, elementClassName: 'noble'},
    
],
//        [
//         {className: 'empty3'},
//    ],
    [
         { abbr: 'La', latinName: 'Thallium', name: 'Dubnium', number: 75, weight: 268, elementClassName: 'lanthanida'},
         { abbr: 'Ce', latinName: 'none', name: 'Seaborgium', number: 76, weight: 271, elementClassName: 'lanthanida'},
         { abbr: 'Pr', latinName: 'none', name: 'Bohtium', number: 77, weight: 272, elementClassName: 'lanthanida'},
         { abbr: 'Nd', latinName: 'none', name: 'Hassium', number: 78, weight: 270, elementClassName: 'lanthanida'},
         { abbr: 'Pm', latinName: 'none', name: 'Meitnerium', number: 79, weight: 276, elementClassName: 'lanthanida'},
         { abbr: 'Sm', latinName: 'Kobold', name: 'Darmstadtium', number: 80, weight: 281, elementClassName: 'lanthanida' },
         { abbr: 'Eu', latinName: 'none', name: 'Roentgenium', number: 81, weight: 280, elementClassName: 'lanthanida' },
         { abbr: 'Gd', latinName: 'none', name: 'Copernicium', number: 82, weight: 285,elementClassName: 'lanthanida' },
         { abbr: 'Tb', latinName: 'none', name: 'Unutrium', number: 83, weight: 284, elementClassName: 'lanthanida' },
         { abbr: 'Dy', latinName: 'Gallium', name: 'Flerovium', number: 84, weight: 289,elementClassName: 'lanthanida' },
         { abbr: 'Ho', latinName: 'Germanium', name: 'Ununpentium', number: 85, weight: 288,elementClassName: 'lanthanida' },
         { abbr: 'Er', latinName: 'Arsenicum', name: 'Livermorium', number: 86, weight: 293,elementClassName: 'lanthanida' },
         { abbr: 'Tm', latinName: 'Bromum', name: 'Ununoctium', number: 88, weight: 294,elementClassName: 'lanthanida' },
         { abbr: 'Yb', latinName: 'Selenium', name: 'Ununseptium', number: 87, weight: 294,elementClassName: 'lanthanida' },
         { abbr: 'Lu', latinName: 'Bromum', name: 'Ununoctium', number: 88, weight: 294,elementClassName: 'lanthanida' },
    ],
     [
         { abbr: 'Ac', latinName: 'Thallium', name: 'Dubnium', number: 75, weight: 268, elementClassName: 'actinade'},
         { abbr: 'Th',  latinName: 'none', name: 'Seaborgium', number: 76, weight: 271, elementClassName: 'actinade'},
         { abbr: 'Pa', latinName: 'none', name: 'Bohtium', number: 77, weight: 272, elementClassName: 'actinade'},
         { abbr: 'U', latinName: 'none', name: 'Hassium', number: 78, weight: 270, elementClassName: 'actinade'},
         { abbr: 'Np', latinName: 'none', name: 'Meitnerium', number: 79, weight: 276, elementClassName: 'actinade'},
         { abbr: 'Pu', latinName: 'Kobold', name: 'Darmstadtium', number: 80, weight: 281, elementClassName: 'actinade'},
         { abbr: 'Am', latinName: 'none', name: 'Roentgenium', number: 81, weight: 280, elementClassName: 'actinade'},
         { abbr: 'Cm', latinName: 'none', name: 'Copernicium', number: 82, weight: 285, elementClassName: 'actinade'},
         { abbr: 'Bk', latinName: 'Berkelium', name: 'Berkelium', number: 83, weight: 284, elementClassName: 'actinade'},
         { abbr: 'Cf', latinName: 'Gallium', name: 'Flerovium', number: 84, weight: 289, elementClassName: 'actinade'},
         { abbr: 'Es', latinName: 'Germanium', name: 'Ununpentium', number: 85, weight: 288, elementClassName: 'actinade'},
         { abbr: 'Fm', latinName: 'Arsenicum', name: 'Livermorium', number: 86, weight: 293, elementClassName: 'actinade'},
         { abbr: 'Md', latinName: 'Bromum', name: 'Ununoctium', number: 88, weight: 294, elementClassName: 'actinade'},
         { abbr: 'No', latinName: 'Nobelium', name: 'Nobelium', number: 87, weight: 294, elementClassName: 'actinade'},
         { abbr: 'Lr', latinName: 'Lawrencium', name: 'Lawrencium', number: 88, weight: 294, elementClassName: 'actinade'}
    ],
],      
slots: [
    {slotName: 'Alkali Metal', elementClassName: 'alkali'}, {slotName: 'Alkaline Earth', elementClassName: 'alkaline'}, {slotName: 'Transition Metal', elementClassName: 'transition'}, {slotName: 'Besic Metal', elementClassName: 'basic'}, {slotName: 'Semimetal', elementClassName: 'semimetal'}, {slotName: 'Nonmetal', elementClassName: 'nonmetal'}, {slotName: 'Halogen', elementClassName: 'halogen'}, {slotName: 'Noble Gas', elementClassName: 'noble'}, {slotName: 'Lanthanida', elementClassName: 'lanthanida'}, {slotName: 'Actinade', elementClassName: 'actinade'}
]};